/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as LandingFaqRouteImport } from './routes/_landing/faq'
import { Route as LandingBlogRouteImport } from './routes/_landing/blog'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as AppUserRouteImport } from './routes/_app/user'
import { Route as AppConnectionNewRouteImport } from './routes/_app/connection/new'
import { Route as AppConnectionConnectionIdRouteImport } from './routes/_app/connection/$connectionId'
import { Route as AppChatConversationIdRouteImport } from './routes/_app/chat/$conversationId'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFaqRoute = LandingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogRoute = LandingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionNewRoute = AppConnectionNewRouteImport.update({
  id: '/connection/new',
  path: '/connection/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionConnectionIdRoute =
  AppConnectionConnectionIdRouteImport.update({
    id: '/connection/$connectionId',
    path: '/connection/$connectionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof AppUserRoute
  '/about': typeof LandingAboutRoute
  '/blog': typeof LandingBlogRoute
  '/faq': typeof LandingFaqRoute
  '/privacy': typeof LandingPrivacyRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/connection/new': typeof AppConnectionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof AppUserRoute
  '/about': typeof LandingAboutRoute
  '/blog': typeof LandingBlogRoute
  '/faq': typeof LandingFaqRoute
  '/privacy': typeof LandingPrivacyRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/connection/new': typeof AppConnectionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_app/user': typeof AppUserRoute
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/blog': typeof LandingBlogRoute
  '/_landing/faq': typeof LandingFaqRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/_app/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/_app/connection/new': typeof AppConnectionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/about'
    | '/blog'
    | '/faq'
    | '/privacy'
    | '/chat/$conversationId'
    | '/connection/$connectionId'
    | '/connection/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/about'
    | '/blog'
    | '/faq'
    | '/privacy'
    | '/chat/$conversationId'
    | '/connection/$connectionId'
    | '/connection/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_landing'
    | '/_app/user'
    | '/_landing/about'
    | '/_landing/blog'
    | '/_landing/faq'
    | '/_landing/privacy'
    | '/_app/chat/$conversationId'
    | '/_app/connection/$connectionId'
    | '/_app/connection/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/faq': {
      id: '/_landing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LandingFaqRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog': {
      id: '/_landing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LandingBlogRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connection/new': {
      id: '/_app/connection/new'
      path: '/connection/new'
      fullPath: '/connection/new'
      preLoaderRoute: typeof AppConnectionNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connection/$connectionId': {
      id: '/_app/connection/$connectionId'
      path: '/connection/$connectionId'
      fullPath: '/connection/$connectionId'
      preLoaderRoute: typeof AppConnectionConnectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$conversationId': {
      id: '/_app/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUserRoute: typeof AppUserRoute
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppConnectionConnectionIdRoute: typeof AppConnectionConnectionIdRoute
  AppConnectionNewRoute: typeof AppConnectionNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUserRoute: AppUserRoute,
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppConnectionConnectionIdRoute: AppConnectionConnectionIdRoute,
  AppConnectionNewRoute: AppConnectionNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingBlogRoute: typeof LandingBlogRoute
  LandingFaqRoute: typeof LandingFaqRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingBlogRoute: LandingBlogRoute,
  LandingFaqRoute: LandingFaqRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
